// Centralised re-exports of lucide-react icons used across the design system.
// Import from "@/design/icons" so we can swap libraries with one edit.

export {
  Mail,
  MapPin,
  MessageSquare,
  Tag,
  FileText,
  Upload,
  Database,
  Search,
  Check,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Minus,
  MoreHorizontal,
  Star,
  AlertCircle,
  AlertTriangle,
  Info,
  Loader2,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Undo2,
  Redo2,
} from "lucide-react";
